#!/bin/bash

if [ $# -eq 0 ]; then
  echo "No resource defined to deploy..."
  exit;
else
  INPUT_FILES=("$@")
  for RESOURCE_FILE in "${INPUT_FILES[@]}"; do
    if [ ! -f "${RESOURCE_FILE}" ]; then
      echo "Resource file ${RESOURCE_FILE} not found..."
    else
      eval $(minikube docker-env)
      echo "Removing any existing definitions for ${RESOURCE_FILE}"
      kubectl delete -f "${RESOURCE_FILE}" || echo "Issue removing ${RESOURCE_FILE} from cluster..."
    fi
  done
fi
