apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gateway
  labels:
    app: service-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-gateway
  template:
    metadata:
      labels:
        app: service-gateway
    spec:
      containers:
        - name: service-gateway
          image: kong:latest
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
            - containerPort: 8444
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_CUSTOM_PLUGINS
              value: "mongo"
            - name: KONG_MONGO_HOSTS
              value: "mongodb:27017"
            - name: KONG_MONG_DB
              value: "gateway"
