#!/bin/bash

minikube status > /dev/null
if [ $? -eq 0 ]; then
  echo "Minikube is running..."
  echo "Checking cluster resources..."
  echo "---"

  echo "ConfigMaps"
  kubectl get configmaps
  echo "---"

  echo "Deployments"
  kubectl get deployments
  echo "---"

  echo "Services"
  kubectl get services
  echo "---"

  echo "Pods"
  kubectl get pods
  echo "---"
  echo

  echo "Checking Docker images available to cluster..."
  eval $(minikube docker-env)
  docker images -f "dangling=false"
else
  echo "Minikube is not running..."
fi
