#!/bin/bash

echo "Checking for Minikube..."
MINIKUBE=$(which minikube)
if [ -z "${MINIKUBE}" ]; then
    echo "Minikube not installed. Install Minikube here: https://kubernetes.io/docs/tasks/tools/install-minikube/"
    exit 1
else
    MINIKUBE_VERSION=$(minikube version | grep -Po "minikube version: \K[^ ]+")
    echo "Minikube is installed! ${MINIKUBE_VERSION}"
fi

echo "Checking Minikube status..."
MINIKUBE_STATUS=$(minikube status)
if [ $? -ne 0 ]; then
    echo "Minikube not running, starting..."
    minikube start --memory=16384 || { echo "Minikube failed to start..."; exit 1; }

    MINIKUBE_STATUS=$(minikube status)
    if [ $? -ne 0 ]; then
        echo "Minikube failed to start..."
        echo $MINIKUBE_STATUS
        exit 1
    fi
else
    echo "Minikube is running..."
fi

MINIKUBE_IP=$(minikube ip)
echo "Minikube is running on ${MINIKUBE_IP}"
